"""Initial migration

Revision ID: 0b71d69509aa
Revises: 
Create Date: 2024-09-09 15:00:59.148129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b71d69509aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('direcciones', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('direcciones', 'calle',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('direcciones', 'ciudad',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('direcciones', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('direcciones', 'pais',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('experiencia_laboral', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('experiencia_laboral', 'empresa',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('experiencia_laboral', 'puesto',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('experiencia_laboral', 'fecha_inicio',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('telefonos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('telefonos', 'numero_telefono',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='Hashed user password')
    op.create_unique_constraint(None, 'usuarios', ['email'])
    op.create_unique_constraint(None, 'usuarios', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='Hashed user password')
    op.alter_column('usuarios', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('telefonos', 'numero_telefono',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('telefonos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('experiencia_laboral', 'fecha_inicio',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('experiencia_laboral', 'puesto',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('experiencia_laboral', 'empresa',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('experiencia_laboral', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('direcciones', 'pais',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('direcciones', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('direcciones', 'ciudad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('direcciones', 'calle',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('direcciones', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
